import { Injectable, OnInit, signal } from '@angular/core';
import { Momahid } from '../models/momahid.model';

@Injectable()
export class MomahidCardService {
  momahidounsList: Array<Momahid> = [
    {
      id: 0,
      pageLanguage: 'ar',
      isStoryVerified: false,
      momahidPhoto: 'img/generic-2.jpg',
      momahidName: 'سعيد',
      momahidAge: 22,
      momahidCountry: 'السودان',
      isMomahidStudy: true,
      isMomahidMarried: false,
      momahidAddictionDuration: 3,
    },
    {
      id: 1,
      pageLanguage: 'ar',
      isStoryVerified: false,
      momahidPhoto: 'img/generic-7.jpg',
      momahidName: 'حمزة',
      momahidAge: 17,
      momahidCountry: 'فلسطين',
      isMomahidStudy: true,
      isMomahidMarried: false,
      momahidAddictionDuration: 2,
    },
    {
      id: 2,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-img.jpg',
      momahidName: 'خالد',
      momahidAge: 29,
      momahidCountry: 'الإمارات',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 7,
    },
    {
      id: 3,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-3.jpg',
      momahidName: 'أحمد',
      momahidAge: 35,
      momahidCountry: 'المغرب',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 9,
    },
    {
      id: 4,
      pageLanguage: 'ar',
      isStoryVerified: false,
      momahidPhoto: 'img/generic-6.jpg',
      momahidName: 'علي',
      momahidAge: 27,
      momahidCountry: 'العراق',
      isMomahidStudy: false,
      isMomahidMarried: false,
      momahidAddictionDuration: 4,
    },
    {
      id: 5,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-1.jpg',
      momahidName: 'محمود',
      momahidAge: 31,
      momahidCountry: 'اليمن',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 11,
    },
    {
      id: 6,
      pageLanguage: 'ar',
      isStoryVerified: false,
      momahidPhoto: 'img/generic-8.jpg',
      momahidName: 'طارق',
      momahidAge: 19,
      momahidCountry: 'سوريا',
      isMomahidStudy: true,
      isMomahidMarried: false,
      momahidAddictionDuration: 4,
    },
    {
      id: 7,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-5.jpg',
      momahidName: 'سيف',
      momahidAge: 24,
      momahidCountry: 'البحرين',
      isMomahidStudy: false,
      isMomahidMarried: false,
      momahidAddictionDuration: 6,
    },
    {
      id: 8,
      pageLanguage: 'ar',
      isStoryVerified: false,
      momahidPhoto: 'img/generic-img.jpg',
      momahidName: 'يوسف',
      momahidAge: 16,
      momahidCountry: 'تونس',
      isMomahidStudy: true,
      isMomahidMarried: false,
      momahidAddictionDuration: 1,
    },
    {
      id: 9,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-4.jpg',
      momahidName: 'زيد',
      momahidAge: 38,
      momahidCountry: 'السعودية',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 12,
    },
    {
      id: 10,
      pageLanguage: 'ar',
      isStoryVerified: false,
      momahidPhoto: 'img/generic-3.jpg',
      momahidName: 'أنس',
      momahidAge: 21,
      momahidCountry: 'الأردن',
      isMomahidStudy: true,
      isMomahidMarried: false,
      momahidAddictionDuration: 3,
    },
    {
      id: 11,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-6.jpg',
      momahidName: 'حسن',
      momahidAge: 26,
      momahidCountry: 'قطر',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 6,
    },
    {
      id: 12,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-7.jpg',
      momahidName: 'عماد',
      momahidAge: 33,
      momahidCountry: 'الكويت',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 8,
    },
    {
      id: 13,
      pageLanguage: 'ar',
      isStoryVerified: false,
      momahidPhoto: 'img/generic-2.jpg',
      momahidName: 'وليد',
      momahidAge: 25,
      momahidCountry: 'لبنان',
      isMomahidStudy: false,
      isMomahidMarried: false,
      momahidAddictionDuration: 5,
    },
    {
      id: 14,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-img.jpg',
      momahidName: 'نادر',
      momahidAge: 30,
      momahidCountry: 'مصر',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 10,
    },
    {
      id: 15,
      pageLanguage: 'ar',
      isStoryVerified: false,
      momahidPhoto: 'img/generic-8.jpg',
      momahidName: 'رامي',
      momahidAge: 18,
      momahidCountry: 'موريتانيا',
      isMomahidStudy: true,
      isMomahidMarried: false,
      momahidAddictionDuration: 2,
    },
    {
      id: 16,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-4.jpg',
      momahidName: 'فارس',
      momahidAge: 34,
      momahidCountry: 'ليبيا',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 9,
    },
    {
      id: 17,
      pageLanguage: 'ar',
      isStoryVerified: false,
      momahidPhoto: 'img/generic-1.jpg',
      momahidName: 'بسام',
      momahidAge: 23,
      momahidCountry: 'جيبوتي',
      isMomahidStudy: false,
      isMomahidMarried: false,
      momahidAddictionDuration: 4,
    },
    {
      id: 18,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-5.jpg',
      momahidName: 'كريم',
      momahidAge: 40,
      momahidCountry: 'عمان',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 13,
    },
    {
      id: 19,
      pageLanguage: 'ar',
      isStoryVerified: false,
      momahidPhoto: 'img/generic-6.jpg',
      momahidName: 'عبدالله',
      momahidAge: 37,
      momahidCountry: 'الصومال',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 11,
    },
    {
      id: 20,
      pageLanguage: 'ar',
      isStoryVerified: true,
      momahidPhoto: 'img/generic-3.jpg',
      momahidName: 'قيس',
      momahidAge: 33,
      momahidCountry: 'عمان',
      isMomahidStudy: false,
      isMomahidMarried: true,
      momahidAddictionDuration: 8,
    },
  ];
}
