import {
  NgLabelTemplateDirective,
  NgOptionTemplateDirective,
  NgSelectComponent,
} from '@ng-select/ng-select';
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import {
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';

@Component({
  selector: 'app-join-momahidoun',
  imports: [
    ReactiveFormsModule,
    NgLabelTemplateDirective,
    NgOptionTemplateDirective,
    NgSelectComponent,
  ],
  templateUrl: './join-momahidoun.component.html',
  styleUrl: './join-momahidoun.component.scss',
})
export class JoinMomahidounComponent {
  // ----
  // momahidName = new FormControl();
  // momahidAge = new FormControl();
  // momahidTypeOfWorkStudy = new FormControl();
  // // ----
  // momahidAgeWhenFirstInteractWithPorn = new FormControl();
  // momahidAddictionDuration = new FormControl();
  // momahidPornDiscovery = new FormControl();
  // previousFailedAttempts = new FormControl();
  // lifeDuringAddiction = new FormControl();
  // // ----
  // lifeAfterTrueTawbah = new FormControl();
  // majorWorshipsThatHealedTheHeart = new FormControl();
  // majorSinsThatPoisonedTheHeart = new FormControl();
  // messageForMomahidBrother = new FormControl();

  momahidForm: FormGroup = new FormGroup({
    momahidName: new FormControl(),
    momahidAge: new FormControl(),
    momahidTypeOfWorkStudy: new FormControl(),
    // ----
    momahidAgeWhenFirstInteractWithPorn: new FormControl(),
    momahidAddictionDuration: new FormControl(),
    momahidPornDiscovery: new FormControl(),
    previousFailedAttempts: new FormControl(),
    lifeDuringAddiction: new FormControl(),
    // ----
    lifeAfterTrueTawbah: new FormControl(),
    majorWorshipsThatHealedTheHeart: new FormControl(),
    majorSinsThatPoisonedTheHeart: new FormControl(),
    messageForMomahidBrother: new FormControl(),
  });

  arWorldCountries = [
    'أفغانستان',
    'ألبانيا',
    'الجزائر',
    'ساموا الأمريكية',
    'أندورا',
    'أنغولا',
    'أنغويلا',
    'القارة القطبية الجنوبية',
    'أنتيغوا وباربودا',
    'الأرجنتين',
    'أرمينيا',
    'أروبا',
    'أستراليا',
    'النمسا',
    'أذربيجان',
    'باهاماس',
    'البحرين',
    'بنغلاديش',
    'باربادوس',
    'روسيا البيضاء',
    'بلجيكا',
    'بليز',
    'بنين',
    'برمودا',
    'بوتان',
    'بوليفيا',
    'البوسنة والهرسك',
    'بوتسوانا',
    'جزيرة بوفيه',
    'البرازيل',
    'إقليم المحيط الهندي البريطاني',
    'بروناي',
    'بلغاريا',
    'بوركينا فاسو',
    'بوروندي',
    'كمبوديا',
    'الكاميرون',
    'كندا',
    'الرأس الأخضر',
    'جزر كايمان',
    'جمهورية أفريقيا الوسطى',
    'تشاد',
    'تشيلي',
    'الصين',
    'جزيرة عيد الميلاد',
    'جزر كوكوس',
    'كولومبيا',
    'جزر القمر',
    'جمهورية الكونغو',
    'جمهورية الكونغو الديمقراطية',
    'جزر كوك',
    'كوستاريكا',
    'ساحل العاج',
    'كرواتيا',
    'كوبا',
    'قبرص',
    'جمهورية التشيك',
    'الدنمارك',
    'جيبوتي',
    'دومينيكا',
    'جمهورية الدومينيكان',
    'الإكوادور',
    'مصر',
    'السلفادور',
    'غينيا الاستوائية',
    'إريتريا',
    'إستونيا',
    'إثيوبيا',
    'جزر فوكلاند',
    'جزر فارو',
    'فيجي',
    'فنلندا',
    'فرنسا',
    'غويانا الفرنسية',
    'بولينزيا الفرنسية',
    'أراض فرنسية جنوبية وأنتارتيكية',
    'الغابون',
    'غامبيا',
    'جورجيا',
    'ألمانيا',
    'غانا',
    'جبل طارق',
    'اليونان',
    'جرينلاند',
    'غرينادا',
    'غوادلوب',
    'غوام',
    'غواتيمالا',
    'غينيا',
    'غينيا بيساو',
    'غيانا',
    'هايتي',
    'جزيرة هيرد وجزر ماكدونالد',
    'الفاتيكان',
    'هندوراس',
    'هونغ كونغ',
    'المجر',
    'آيسلندا',
    'الهند',
    'إندونيسيا',
    'إيران',
    'العراق',
    'أيرلندا',
    'إيطاليا',
    'جامايكا',
    'اليابان',
    'الأردن',
    'كازاخستان',
    'كينيا',
    'كيريباتي',
    'كوريا الشمالية',
    'كوريا الجنوبية',
    'الكويت',
    'قيرغيزستان',
    'لاوس',
    'لاتفيا',
    'لبنان',
    'ليسوتو',
    'ليبيريا',
    'ليبيا',
    'ليختنشتاين',
    'ليتوانيا',
    'لوكسمبورغ',
    'ماكاو',
    'مقدونيا الشمالية',
    'مدغشقر',
    'مالاوي',
    'ماليزيا',
    'جزر المالديف',
    'مالي',
    'مالطا',
    'جزر مارشال',
    'مارتينيك',
    'موريتانيا',
    'موريشيوس',
    'مايوت',
    'المكسيك',
    'ولايات ميكرونيسيا المتحدة',
    'مولدوفا',
    'موناكو',
    'منغوليا',
    'مونتسرات',
    'المغرب',
    'موزمبيق',
    'بورما',
    'ناميبيا',
    'ناورو',
    'نيبال',
    'هولندا',
    'كاليدونيا الجديدة',
    'نيوزيلندا',
    'نيكاراغوا',
    'النيجر',
    'نيجيريا',
    'نييوي',
    'جزيرة نورفولك',
    'جزر ماريانا الشمالية',
    'النرويج',
    'عمان',
    'باكستان',
    'بالاو',
    'فلسطين',
    'بنما',
    'بابوا غينيا الجديدة',
    'باراغواي',
    'بيرو',
    'الفلبين',
    'جزر بيتكيرن',
    'بولندا',
    'البرتغال',
    'بورتوريكو',
    'قطر',
    'لا ريونيون',
    'رومانيا',
    'روسيا',
    'رواندا',
    'سانت هيلينا وأسينشين وتريستان دا كونا',
    'سانت كيتس ونيفيس',
    'سانت لوسيا',
    'سان بيير وميكلون',
    'سانت فينسنت والغرينادين',
    'ساموا',
    'سان مارينو',
    'ساو تومي وبرينسيب',
    'السعودية',
    'السنغال',
    'سيشل',
    'سيراليون',
    'سنغافورة',
    'سلوفاكيا',
    'سلوفينيا',
    'جزر سليمان',
    'الصومال',
    'جنوب أفريقيا',
    'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
    'إسبانيا',
    'سريلانكا',
    'السودان',
    'سورينام',
    'سفالبارد ويان ماين',
    'سوازيلاند',
    'السويد',
    'سويسرا',
    'سوريا',
    'تايوان',
    'طاجيكستان',
    'تانزانيا',
    'تايلاند',
    'تيمور الشرقية',
    'توغو',
    'توكيلاو',
    'تونغا',
    'ترينيداد وتوباغو',
    'تونس',
    'تركيا',
    'تركمانستان',
    'جزر توركس وكايكوس',
    'توفالو',
    'أوغندا',
    'أوكرانيا',
    'الإمارات العربية المتحدة',
    'المملكة المتحدة',
    'الولايات المتحدة',
    'جزر الولايات المتحدة',
    'الأوروغواي',
    'أوزبكستان',
    'فانواتو',
    'فنزويلا',
    'فيتنام',
    'جزر العذراء البريطانية',
    'جزر العذراء الأمريكية',
    'والس وفوتونا',
    'الصحراء الغربية',
    'اليمن',
    'زامبيا',
    'زيمبابوي',
    'جزر أولاند',
    'الجزر الكاريبية الهولندية',
    'كوراساو',
    'غيرنزي',
    'جزيرة مان',
    'جيرزي',
    'الجبل الأسود',
    'سان بارتيلمي',
    'سانت مارتن (الجزء الفرنسي)',
    'صربيا',
    'سانت مارتن (الجزء الهولندي)',
    'جنوب السودان',
    'كوسوفو',
  ];
  constructor(private http: HttpClient) {}

  submitMomahidRequest() {
    const obj = this.momahidForm.value;

    console.log(obj);
    this.http
      .post('http://localhost:3000/al-momahidoun', obj)
      .subscribe((res: any) => alert('The requested saved successfully!'));
  }
}
